### ISSUE TITLE
LevelDB folder location not available

### ISSUE THREAD

**Issue by Kazetsukai** [tcoats/tumu-host#1]
`UnhandledPromiseRejectionWarning: OpenError: IO error: /Users/danieltebbutt/.data/access/LOCK: No such file or directory
    at /usr/local/lib/node_modules/tumu-host/node_modules/levelup/lib/levelup.js:87:23
    at /usr/local/lib/node_modules/tumu-host/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at /usr/local/lib/node_modules/tumu-host/node_modules/deferred-leveldown/deferred-leveldown.js:20:21
    at /usr/local/lib/node_modules/tumu-host/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at /usr/local/lib/node_modules/tumu-host/node_modules/abstract-leveldown/abstract-leveldown.js:41:14`

**Comment by Kazetsukai** [comment]
Might not be LevelDB not being installed, as that should come from dependencies? I needed to mkdir .data and .data/access as a workaround.

**Comment by tcoats** [comment]
Thank you - fixed in v0.2.3
